function data = generateRayleighTable(M, gamma)
%GENERATERAYLEIGHTABLE Generate a Rayleigh-flow property table.
%
%   data = generateRayleighTable(M, gamma)
%
%   Generates Rayleigh-flow properties for supplied Mach numbers.
%
%   Reference state:
%       M* = 1

    narginchk(2, 2);

    validateInput(M, gamma);

    M = M(:);

    pRatio = pressureRatio(M, gamma);
    TRatio = temperatureRatio(M, gamma);
    rhoRatio = densityRatio(M, gamma);
    VRatio = velocityRatio(M, gamma);
    T0Ratio = stagnationTemperatureRatio(M, gamma);
    p0Ratio = stagnationPressureRatio(M, gamma);
    dsOverR = entropyChange(M, gamma);
    qOverCpTstar = heatAddition(M, gamma);

    data = table( ...
        M, ...
        pRatio, ...
        TRatio, ...
        rhoRatio, ...
        VRatio, ...
        T0Ratio, ...
        p0Ratio, ...
        dsOverR, ...
        qOverCpTstar, ...
        'VariableNames', { ...
            'Mach', ...
            'PressureRatio', ...
            'TemperatureRatio', ...
            'DensityRatio', ...
            'VelocityRatio', ...
            'StagnationTemperatureRatio', ...
            'StagnationPressureRatio', ...
            'EntropyOverR', ...
            'HeatAdditionOverCpTstar' ...
        });

end